-- =====================================================================
-- V1 baseline: 사용자 / 커플 space / 초대 페어링 / 리프레시 토큰
-- =====================================================================

-- ---------------------------------------------------------------------
-- users : 소셜 로그인 사용자
-- ---------------------------------------------------------------------
CREATE TABLE users
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider          VARCHAR(20)  NOT NULL,
    provider_id       VARCHAR(255) NOT NULL,
    email             VARCHAR(255),
    nickname          VARCHAR(50)  NOT NULL,
    profile_image_url TEXT,
    status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_users_provider CHECK (provider IN ('KAKAO', 'GOOGLE')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'WITHDRAWN')),
    CONSTRAINT uq_users_provider_identity UNIQUE (provider, provider_id)
);

COMMENT ON TABLE users IS '소셜 로그인 사용자';
COMMENT ON COLUMN users.provider_id IS 'OAuth 제공자가 발급한 고유 식별자';

-- ---------------------------------------------------------------------
-- accounts : 정산 화면에 표시할 입금 계좌 (사용자당 1개)
-- ---------------------------------------------------------------------
CREATE TABLE accounts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    bank_code   VARCHAR(10) NOT NULL,
    bank_name   VARCHAR(50) NOT NULL,
    account_no  VARCHAR(128) NOT NULL,
    holder_name VARCHAR(50) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_accounts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_accounts_user UNIQUE (user_id)
);

COMMENT ON TABLE accounts IS '정산 시 표시/복사할 입금 계좌';
COMMENT ON COLUMN accounts.account_no IS '암호화되어 저장되는 계좌번호';

-- ---------------------------------------------------------------------
-- couples : 커플 space (정확히 2인)
-- ---------------------------------------------------------------------
CREATE TABLE couples
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(50) NOT NULL,
    created_by    BIGINT      NOT NULL,
    status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    settlement_day SMALLINT   NOT NULL DEFAULT 1,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_couples_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_couples_status CHECK (status IN ('PENDING', 'ACTIVE', 'DISBANDED')),
    CONSTRAINT ck_couples_settlement_day CHECK (settlement_day BETWEEN 1 AND 28)
);

COMMENT ON TABLE couples IS '커플 공유 space';
COMMENT ON COLUMN couples.status IS 'PENDING=파트너 대기, ACTIVE=2인 연결 완료, DISBANDED=해제';
COMMENT ON COLUMN couples.settlement_day IS '월 정산 기준일. 말일 문제를 피하려 1~28로 제한';

-- ---------------------------------------------------------------------
-- couple_members : 커플 구성원. member_no 로 "2인 고정"을 DB가 강제한다.
-- ---------------------------------------------------------------------
CREATE TABLE couple_members
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id BIGINT      NOT NULL,
    user_id   BIGINT      NOT NULL,
    member_no SMALLINT    NOT NULL,
    role      VARCHAR(20) NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    left_at   TIMESTAMPTZ,
    CONSTRAINT fk_couple_members_couple FOREIGN KEY (couple_id) REFERENCES couples (id),
    CONSTRAINT fk_couple_members_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_couple_members_role CHECK (role IN ('OWNER', 'PARTNER')),
    -- 한 space 안에 자리는 1번/2번 둘뿐 -> 3인 이상 진입 불가
    CONSTRAINT ck_couple_members_member_no CHECK (member_no IN (1, 2)),
    CONSTRAINT uq_couple_members_slot UNIQUE (couple_id, member_no),
    CONSTRAINT uq_couple_members_user UNIQUE (couple_id, user_id)
);

-- 한 사용자는 동시에 하나의 커플에만 소속된다 (탈퇴하면 다시 가능)
CREATE UNIQUE INDEX uq_couple_members_active_user
    ON couple_members (user_id)
    WHERE left_at IS NULL;

COMMENT ON TABLE couple_members IS '커플 구성원. member_no(1|2) 유니크 제약으로 2인 고정을 보장';

-- ---------------------------------------------------------------------
-- couple_invites : 파트너 초대 링크. 원문 토큰은 저장하지 않고 해시만 보관.
-- ---------------------------------------------------------------------
CREATE TABLE couple_invites
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id   BIGINT      NOT NULL,
    inviter_id  BIGINT      NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    accepted_at TIMESTAMPTZ,
    accepted_by BIGINT,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_couple_invites_couple FOREIGN KEY (couple_id) REFERENCES couples (id),
    CONSTRAINT fk_couple_invites_inviter FOREIGN KEY (inviter_id) REFERENCES users (id),
    CONSTRAINT fk_couple_invites_accepted_by FOREIGN KEY (accepted_by) REFERENCES users (id),
    CONSTRAINT uq_couple_invites_token UNIQUE (token_hash)
);

-- 커플당 살아있는 초대는 하나만
CREATE UNIQUE INDEX uq_couple_invites_active
    ON couple_invites (couple_id)
    WHERE accepted_at IS NULL AND revoked_at IS NULL;

COMMENT ON TABLE couple_invites IS '파트너 페어링 초대. token_hash = SHA-256(raw token)';

-- ---------------------------------------------------------------------
-- refresh_tokens : 회전(rotation) + 재사용 탐지용 저장소
-- ---------------------------------------------------------------------
CREATE TABLE refresh_tokens
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    family_id   UUID        NOT NULL,
    token_hash  VARCHAR(64) NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_refresh_tokens_token UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_tokens_family ON refresh_tokens (family_id);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

COMMENT ON TABLE refresh_tokens IS '리프레시 토큰 회전 이력. 이미 사용된 토큰이 다시 오면 family 전체를 폐기';
COMMENT ON COLUMN refresh_tokens.family_id IS '최초 로그인 1건에서 파생된 회전 체인 식별자';
