-- =====================================================================
-- V2 : 지출 기록 / 월 정산 사이클
--   금액은 모두 "원" 단위 정수(BIGINT). 부동소수점을 쓰지 않는다.
-- =====================================================================

-- ---------------------------------------------------------------------
-- settlements : 커플-기간(YYYYMM) 단위의 정산. (couple_id, period) 유니크가 멱등성 보장.
-- ---------------------------------------------------------------------
CREATE TABLE settlements
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id    BIGINT      NOT NULL,
    period       VARCHAR(6)  NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    net_amount   BIGINT      NOT NULL DEFAULT 0,
    creditor_id  BIGINT,
    debtor_id    BIGINT,
    confirmed_at TIMESTAMPTZ,
    confirmed_by BIGINT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_settlements_couple FOREIGN KEY (couple_id) REFERENCES couples (id),
    CONSTRAINT fk_settlements_creditor FOREIGN KEY (creditor_id) REFERENCES users (id),
    CONSTRAINT fk_settlements_debtor FOREIGN KEY (debtor_id) REFERENCES users (id),
    CONSTRAINT fk_settlements_confirmed_by FOREIGN KEY (confirmed_by) REFERENCES users (id),
    CONSTRAINT ck_settlements_status CHECK (status IN ('OPEN', 'CONFIRMED')),
    CONSTRAINT ck_settlements_period CHECK (period ~ '^[0-9]{6}$'),
    CONSTRAINT ck_settlements_net_amount CHECK (net_amount >= 0),
    -- 정산이 0원이면 채권자/채무자가 없고, 0원이 아니면 둘 다 있어야 하며 서로 달라야 한다
    CONSTRAINT ck_settlements_direction CHECK (
        (net_amount = 0 AND creditor_id IS NULL AND debtor_id IS NULL)
            OR (net_amount > 0 AND creditor_id IS NOT NULL AND debtor_id IS NOT NULL AND creditor_id <> debtor_id)
        ),
    CONSTRAINT ck_settlements_confirmed CHECK (
        (status = 'OPEN' AND confirmed_at IS NULL AND confirmed_by IS NULL)
            OR (status = 'CONFIRMED' AND confirmed_at IS NOT NULL AND confirmed_by IS NOT NULL)
        ),
    -- 같은 기간을 두 번 정산할 수 없다 (확정 API 멱등성의 근거)
    CONSTRAINT uq_settlements_couple_period UNIQUE (couple_id, period)
);

COMMENT ON TABLE settlements IS '월 단위 정산. (couple_id, period) 유니크로 중복 확정을 DB가 차단';
COMMENT ON COLUMN settlements.period IS '정산 대상 월. YYYYMM 형식. CHAR 의 공백 패딩을 피하려 VARCHAR 로 둔다';
COMMENT ON COLUMN settlements.net_amount IS 'debtor 가 creditor 에게 보낼 순잔액(원). 항상 0 이상';

-- ---------------------------------------------------------------------
-- expenses : 지출 기록
-- ---------------------------------------------------------------------
CREATE TABLE expenses
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id         BIGINT      NOT NULL,
    payer_id          BIGINT      NOT NULL,
    amount            BIGINT      NOT NULL,
    category          VARCHAR(30) NOT NULL,
    payer_burden_rate SMALLINT    NOT NULL DEFAULT 50,
    spent_at          DATE        NOT NULL,
    memo              VARCHAR(255),
    settlement_id     BIGINT,
    created_by        BIGINT      NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at        TIMESTAMPTZ,
    CONSTRAINT fk_expenses_couple FOREIGN KEY (couple_id) REFERENCES couples (id),
    CONSTRAINT fk_expenses_payer FOREIGN KEY (payer_id) REFERENCES users (id),
    CONSTRAINT fk_expenses_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_expenses_settlement FOREIGN KEY (settlement_id) REFERENCES settlements (id),
    CONSTRAINT ck_expenses_amount CHECK (amount > 0),
    CONSTRAINT ck_expenses_burden_rate CHECK (payer_burden_rate BETWEEN 0 AND 100),
    CONSTRAINT ck_expenses_category CHECK (category IN (
        'RENT', 'UTILITY', 'GROCERY', 'DINING', 'DATE',
        'TRANSPORT', 'SHOPPING', 'TRAVEL', 'SUBSCRIPTION', 'ETC'
        ))
);

-- 월별 뷰 / 순잔액 집계의 주 접근 경로
CREATE INDEX idx_expenses_couple_spent_at
    ON expenses (couple_id, spent_at DESC)
    WHERE deleted_at IS NULL;

-- 확정 정산에 귀속된 건을 찾을 때
CREATE INDEX idx_expenses_settlement ON expenses (settlement_id) WHERE settlement_id IS NOT NULL;

COMMENT ON TABLE expenses IS '공동생활비·데이트비 지출 기록';
COMMENT ON COLUMN expenses.payer_burden_rate IS '이 지출에서 결제자 본인이 부담할 비율(%). 50이면 반반. 상대가 갚을 몫 = amount * (100 - rate) / 100';
COMMENT ON COLUMN expenses.settlement_id IS '확정된 정산에 귀속되면 채워지고, 이후 수정/삭제가 잠긴다';
