-- =====================================================================
-- V3 : 반복지출(월세·공과금·구독) / 카테고리별 부담비율 프리셋
-- =====================================================================

-- ---------------------------------------------------------------------
-- recurring_expenses : 매달 같은 날 같은 금액으로 나가는 지출의 정의
-- ---------------------------------------------------------------------
CREATE TABLE recurring_expenses
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id         BIGINT      NOT NULL,
    payer_id          BIGINT      NOT NULL,
    title             VARCHAR(50) NOT NULL,
    amount            BIGINT      NOT NULL,
    category          VARCHAR(30) NOT NULL,
    payer_burden_rate SMALLINT    NOT NULL DEFAULT 50,
    day_of_month      SMALLINT    NOT NULL,
    memo              VARCHAR(255),
    active            BOOLEAN     NOT NULL DEFAULT TRUE,
    starts_on         DATE        NOT NULL,
    ends_on           DATE,
    created_by        BIGINT      NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_recurring_expenses_couple FOREIGN KEY (couple_id) REFERENCES couples (id),
    CONSTRAINT fk_recurring_expenses_payer FOREIGN KEY (payer_id) REFERENCES users (id),
    CONSTRAINT fk_recurring_expenses_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT ck_recurring_expenses_amount CHECK (amount > 0),
    CONSTRAINT ck_recurring_expenses_burden_rate CHECK (payer_burden_rate BETWEEN 0 AND 100),
    -- 29~31일은 없는 달이 있어 발생일에서 제외한다 (couples.settlement_day 와 같은 이유)
    CONSTRAINT ck_recurring_expenses_day CHECK (day_of_month BETWEEN 1 AND 28),
    CONSTRAINT ck_recurring_expenses_period CHECK (ends_on IS NULL OR ends_on >= starts_on),
    CONSTRAINT ck_recurring_expenses_category CHECK (category IN (
        'RENT', 'UTILITY', 'GROCERY', 'DINING', 'DATE',
        'TRANSPORT', 'SHOPPING', 'TRAVEL', 'SUBSCRIPTION', 'ETC'
        ))
);

CREATE INDEX idx_recurring_expenses_due ON recurring_expenses (day_of_month) WHERE active;

COMMENT ON TABLE recurring_expenses IS '월세·공과금·구독처럼 매달 반복되는 지출의 정의. 실제 지출은 스케줄러가 만든다';
COMMENT ON COLUMN recurring_expenses.starts_on IS '이 날짜 이후의 발생일부터 생성한다. 등록 즉시 지난 달치가 만들어지는 것을 막는다';
COMMENT ON COLUMN recurring_expenses.ends_on IS '구독 해지일처럼 반복이 끝나는 날. null 이면 무기한';

-- ---------------------------------------------------------------------
-- expenses.recurring_expense_id : 어느 반복지출에서 생성됐는지
-- ---------------------------------------------------------------------
ALTER TABLE expenses
    ADD COLUMN recurring_expense_id BIGINT,
    ADD CONSTRAINT fk_expenses_recurring FOREIGN KEY (recurring_expense_id) REFERENCES recurring_expenses (id);

-- 한 반복지출은 한 달에 한 건만 만든다.
-- 스케줄러가 여러 번 돌아도(재시작·다중 인스턴스) DB 가 중복을 막는다.
-- 사용자가 지운 건(deleted_at)도 조건에서 빼지 않는다. 지운 것을 다시 만들어 주면 안 되기 때문이다.
-- to_char 는 로케일에 따라 결과가 달라질 수 있어 IMMUTABLE 이 아니고, 인덱스 식으로 쓸 수 없다.
-- date_trunc(text, timestamp) 는 IMMUTABLE 이라 인덱스에 들어간다.
CREATE UNIQUE INDEX uq_expenses_recurring_period
    ON expenses (recurring_expense_id, date_trunc('month', spent_at::timestamp))
    WHERE recurring_expense_id IS NOT NULL;

COMMENT ON COLUMN expenses.recurring_expense_id IS '반복지출에서 자동 생성된 건이면 그 정의를 가리킨다';

-- ---------------------------------------------------------------------
-- category_burden_presets : 카테고리마다 미리 정해 둔 부담 비율
-- ---------------------------------------------------------------------
CREATE TABLE category_burden_presets
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_id           BIGINT      NOT NULL,
    category            VARCHAR(30) NOT NULL,
    member1_burden_rate SMALLINT    NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_category_burden_presets_couple FOREIGN KEY (couple_id) REFERENCES couples (id),
    CONSTRAINT uq_category_burden_presets UNIQUE (couple_id, category),
    CONSTRAINT ck_category_burden_presets_rate CHECK (member1_burden_rate BETWEEN 0 AND 100),
    CONSTRAINT ck_category_burden_presets_category CHECK (category IN (
        'RENT', 'UTILITY', 'GROCERY', 'DINING', 'DATE',
        'TRANSPORT', 'SHOPPING', 'TRAVEL', 'SUBSCRIPTION', 'ETC'
        ))
);

COMMENT ON TABLE category_burden_presets IS '카테고리별 기본 부담 비율. 지출 등록 시 비율을 생략하면 여기서 가져온다';
COMMENT ON COLUMN category_burden_presets.member1_burden_rate IS
    '1번 자리(OWNER)가 부담할 비율(%). 결제자 기준이 아니라 사람 기준이라, 누가 결제하든 부담은 같다';
