-- =====================================================================
-- V4 : 알림 (정산일 리마인드 등)
-- =====================================================================

CREATE TABLE notifications
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL,
    couple_id  BIGINT       NOT NULL,
    type       VARCHAR(40)  NOT NULL,
    title      VARCHAR(100) NOT NULL,
    body       VARCHAR(255) NOT NULL,
    period     VARCHAR(6),
    read_at    TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_notifications_couple FOREIGN KEY (couple_id) REFERENCES couples (id),
    CONSTRAINT ck_notifications_type CHECK (type IN ('SETTLEMENT_REMINDER')),
    CONSTRAINT ck_notifications_period CHECK (period IS NULL OR period ~ '^[0-9]{6}$')
);

-- 알림함은 언제나 "내 것을 최신순으로"만 읽는다
CREATE INDEX idx_notifications_user_created ON notifications (user_id, created_at DESC);

-- 같은 사람에게 같은 종류·같은 기간의 알림을 두 번 보내지 않는다.
-- 스케줄러가 하루에 여러 번 돌아도(재시작·다중 인스턴스) 알림은 한 번이다.
CREATE UNIQUE INDEX uq_notifications_dedupe
    ON notifications (user_id, type, period)
    WHERE period IS NOT NULL;

COMMENT ON TABLE notifications IS '인앱 알림. SSE 로 실시간 전달되고 알림함에서 다시 볼 수 있다';
COMMENT ON COLUMN notifications.period IS '관련 정산 기간(YYYYMM). 중복 발송 방지 키로도 쓴다';
